#!/usr/bin/env python3
"""Generate .env from .env.example on first deployment.

Usage:
    python3 setup_env.py              # interactive prompts
    python3 setup_env.py --defaults   # accept all defaults (CI/testing)
    python3 setup_env.py --force      # overwrite existing .env
"""

import argparse
import os
import secrets
import shutil
import sys

ENV_FILE = '.env'
EXAMPLE_FILE = '.env.example'


def generate_secret_key():
    return secrets.token_hex(32)


def prompt(key, default, description, auto):
    if auto:
        return default
    display = f'[{default}]' if default else '[required]'
    val = input(f'{description} {display}: ').strip()
    return val or default


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--defaults', action='store_true', help='Accept all defaults without prompting')
    parser.add_argument('--force', action='store_true', help='Overwrite existing .env')
    args = parser.parse_args()

    if os.path.exists(ENV_FILE) and not args.force:
        print(f'{ENV_FILE} already exists. Use --force to overwrite.')
        sys.exit(0)

    if not os.path.exists(EXAMPLE_FILE):
        print(f'{EXAMPLE_FILE} not found.')
        sys.exit(1)

    auto = args.defaults

    secret_key = generate_secret_key()
    pg_password = prompt('POSTGRES_PASSWORD', secrets.token_urlsafe(16), 'PostgreSQL password', auto)
    pg_user = prompt('POSTGRES_USER', 'ng4', 'PostgreSQL user', auto)
    pg_db = prompt('POSTGRES_DB', 'ng4', 'PostgreSQL database name', auto)
    db_url = prompt('DATABASE_URL', f'postgresql://{pg_user}:{pg_password}@db:5432/{pg_db}', 'SQLAlchemy DATABASE_URL', auto)
    cache_type = prompt('CACHE_TYPE', 'RedisCache', 'Cache type (SimpleCache / RedisCache)', auto)
    redis_url = prompt('REDIS_URL', 'redis://redis:6379/0', 'Redis URL', auto)
    concurrency = prompt('WEB_CONCURRENCY', '4', 'Gunicorn worker count', auto)
    app_port = prompt('APP_PORT', '127.0.0.1:8001', 'App host port for external proxy (e.g. NPM)', auto)

    lines = [
        '# Auto-generated by setup_env.py — for Docker/production use only.\n',
        '# Do not source this file for local development; SQLite is used by default.\n',
        'FLASK_ENV=production\n',
        f'SECRET_KEY={secret_key}\n',
        f'POSTGRES_PASSWORD={pg_password}\n',
        f'POSTGRES_USER={pg_user}\n',
        f'POSTGRES_DB={pg_db}\n',
        f'DATABASE_URL={db_url}\n',
        f'CACHE_TYPE={cache_type}\n',
        f'REDIS_URL={redis_url}\n',
        f'WEB_CONCURRENCY={concurrency}\n',
        f'APP_PORT={app_port}\n',
    ]

    with open(ENV_FILE, 'w') as f:
        f.writelines(lines)

    print(f'{ENV_FILE} created.')
    if not auto:
        print(f'  SECRET_KEY  = {secret_key}')


if __name__ == '__main__':
    main()
